spring:
  application:
    name: Product Management API
    version: 1.0.0
  banner:
    location: classpath:banner.txt
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/product-management}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  profiles:
    active: Development