server:
  servlet:
    context-path: /api/v1
  port: 8080
  shutdown: graceful

email-server:
  key: 776ee04896f1b54148bf07acaef1d6c9

spring:
  application:
    name: Product Management API
    version: 1.0.0
  banner:
    location: classpath:banner.txt
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/product-management}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:xwm@kyv9ydn1JPW.dch}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      jdbc:
        time_zone: UTC
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  profiles:
    active: Development

  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: UTC

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  override-with-generic-response: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %magenta([%t]) %m%n"